name: build ios and upload to testflight
on:
  push:
    branches:
      - 'beta'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: flutter build ipa
        uses: subosito/flutter-action@v2.16.0
        with:
          channel: stable
          cache: true
      - run: flutter --version
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign
      - run: fastlane beta
      - run: cd ios
      - run: fastlane beta
