name: Deploy Appstore

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy-appstore:
    name: Deploy Appstore
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          ref: 'master'
      
      - name: Decode Firebase Options
        run: echo "${{ secrets.FIREBASE_OPTIONS }}" > lib/firebase_options.dart
      
      - name: Decode Google Service Info Plist
        run : echo "${{ secrets.GOOGLE_SERVICE_INFO_PLIST}}" > ios/Runner/GoogleService-Info.plist

      - name: Decode firebase.json
        run : echo '${{ secrets.FIREBASE_JSON }}' > firebase.json

      - name: make env directory
        run: mkdir env

      - name: add .env file
        run: echo "API_URI=https://prod-next.dimipay.io/" > env/.env
      
      - name: Install flutter sdk
        uses: subosito/flutter-action@v2.16.0
        with:
          channel: stable
          cache: true
          flutter-version-file: pubspec.yaml
      - run: flutter --version
      - run: dart pub global activate flutterfire_cli
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign
      - run: fastlane prod
        working-directory: ./ios
        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          APPLE_DEV_USERNAME: ${{ secrets.APPLE_DEV_USERNAME }}
          APPSTORECONNECT_API_KEY_ID: ${{ secrets.APPSTORECONNECT_API_KEY_ID }}
          APPSTORECONNECT_API_ISSUER_ID: ${{ secrets.APPSTORECONNECT_API_ISSUER_ID }}
          APPSTORECONNECT_API_KEY: ${{ secrets.APPSTORECONNECT_API_KEY }}
